version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: fork-ts-checker-webpack-plugin
    versions:
    - 6.1.0
    - 6.1.1
    - 6.2.0
    - 6.2.1
    - 6.2.4
  - dependency-name: antd
    versions:
    - 4.11.2
    - 4.12.1
    - 4.12.2
    - 4.12.3
    - 4.13.0
    - 4.13.1
    - 4.14.0
    - 4.14.1
    - 4.15.0
    - 4.15.1
    - 4.15.2
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.0
    - 17.0.1
    - 17.0.2
  - dependency-name: typescript-plugin-css-modules
    versions:
    - 3.1.0
